### ISSUE TITLE
Utilize ``/policies/instance`` on listing instance properties

### ISSUE THREAD

**Issue by Thesourtimes** [fosscord/fosscord-community-instances#17]
This endpoint might be used on deployment of instance list. It has some pros and cons

> Pros
+ Instance owners can easily do changes about their instance's general info and It will be updated in next deployment without any PR or something.
+ Instance listing will be decentralized.

> Cons
- Uptime might be a problem.
- Slower deployment.

**Comment by Intevel** [comment]
We will soon release a new version of the instance list, the instance owners will be given more options. I close this issue
