### ISSUE TITLE
mugman fosscord instance

### ISSUE THREAD

**Issue by mugman174** [fosscord/fosscord-community-instances#7]
My Fosscord instance: http://199.241.139.181:3001/
Description: mugman's Fosscord instance for chatting, coding, and more.
Discord Server: https://discord.gg/m6UjFzqhAg

**Comment by mugman174** [comment]
Ignore this issue, will make PR soon:tm:

**Comment by Denisbg2011game** [comment]
https://denisfosscord.run-eu-central1.goorm.io/invite/QopGSU 

fosscord invite to my server
